import numpy as np

a = np.array([1,2,3,4])
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b.dtype)
print(b.ndim)
print(type(b))
print(np.arange(1,11))
print(np.arange(1,11,2))
print(np.zeros((3,2)))
print(np.ones((3,2)))
print(np.eye(3))
print(np.full((3,3),2))
print(np.full((3,3),2.2, dtype=np.int))
print(np.diag([1,2,3,4,5]))
v = np.array([1,2,3])
print(np.tile(v,(3,1)))
print(50*np.random.random()+2)
print(50*np.random.random([3,3])+2)
print(np.linspace(1,50,100))
print(np.arange(18).reshape(2,3,3))
a = np.array([1,2,3])
print(a[1])
print(a[1:])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c[2,2])
print(c > 2)
print(c[c>2])
print(c[(c>2) & (c<5)])
print(c.T)
print((c==b))
print(np.sin(a))
print(np.sum(a))
print(np.median(a))
print(np.std(a))
print(np.linalg.det(c))
print(np.linalg.inv(c))
print(np.max(a))